spring:
    application:
        name: aiservice
    config:
        import: optional:configserver:http://localhost:8888 #aiservice application.yml is loaded from http://localhost:8888/aiservice/default