spring:
    application:
        name: userservice
    config:
        import: optional:configserver:http://localhost:8888 #userservice application.yml is loaded from http://localhost:8888/userservice/default